[package]
name = "control-plane"
version = "0.1.0"
edition = "2021"


[dependencies]
api.workspace = true

anyhow.workspace = true
axum.workspace = true
reqwest.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
