[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
derive_more.workspace = true
minio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
